### ISSUE TITLE
Pull all 10 variables to AWS

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nwp#13]
## Detailed Description
Currently in AWS there are only 4. 

## Context
New modesl need 10 variables 
I think the order is updated, or is atleast ready to go.

## Possible Implementation
- not sure, check the correct order is being used. 
- check that the other variables dont get stripped out somewhere

**Comment by devsjc** [comment]
Update ORDER_IDS secret value to new order id:
- [x] [dev](https://eu-west-1.console.aws.amazon.com/secretsmanager/secret?name=development%2Fconsumer%2Fnwp&region=eu-west-1

**Comment by peterdudfield** [comment]
This done on production too? @devsjc
