### ISSUE TITLE
Download latest UKV GRIB files onto `leonardo` from CEDA

### ISSUE THREAD

**Issue by JackKelly** [openclimatefix/nwp#21]

**Comment by JackKelly** [comment]
Sure!

GRIB files go in: `/mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/NWP/UK_Met_Office/UKV/native/`

Please note the directory structure already present in that directory.

This directory already has files up to Feb 2023. So please can we download the files from the end of the current GRIB dataset, to today?

Zarr datasets go in: `/mnt/storage_b/data/ocf/solar_pv_nowcasting/nowcasting_dataset_pipeline/NWP/UK_Met_Office/UKV/zarr/`



@jacobbieker is this correct?

**Comment by jacobbieker** [comment]
That directory is correct. The files from Oct/November 2021 to Feb 2023 aren't actually GRIB files apparently, when I tried appending them with the script in here to the NWP zarr, it threw errors, and apparently when I downloaded them the contents aren't right. So would recommend redownloading from the last date in the NWP Zarr. 

The path for the zarr dataset is also correct. There are currently 3 variants of the NWP zarr in `/mnt/storage_c/` but they should probably just be moved over for now

**Comment by devsjc** [comment]
I see what you're saying about the structure of the gribs - I'm having trouble with the Zarr conversion also. What I'll do so as to not hold up proceedings is set it downloading just the native files for now whilst in investigate the conversion side of things.

**Comment by devsjc** [comment]
One thing worth raising is that in the consumer so far I've avoided downloading anything beyond wholesale 2, as the variables in wholesale 3 onwards are not variables that are available in the live data we pull from MetOffice. Do you still want everything pulling from CEDA or just stuff we can access in the live dataset? 

Also, those dodgy grib files on leonardo are actually HTML files explaining that you aren't logged in to CEDA! No wonder zarr didn't like them!

**Comment by jacobbieker** [comment]
I think we would just want the ones that are available during live data, so yeah, I would ignore the wholesale3 ones, right @JackKelly?

And that makes a lot more sense! Thanks for figuring that out

**Comment by devsjc** [comment]
Should I delete the HTML datasets back to the correct time in 2021 and then redownload from there to now?

**Comment by jacobbieker** [comment]
Yeah, that would be great

**Comment by devsjc** [comment]
Ah I'm not sure I have permission to do that actually, seems they are write protected and I can't delete them nor change the perms to enable it. The first HTML files appear for the 1800 hours run in 2021/11/08.

**Comment by jacobbieker** [comment]
I've started deleting those ones, it should be free soon

**Comment by jacobbieker** [comment]
Should be done now

**Comment by devsjc** [comment]
Cheers @jacobbieker!

**Comment by devsjc** [comment]
@JackKelly you mentioned you wanted to play with the full 52 hour forecasting horizon, by which I assume you're meaning the 52 time steps in each run. However again currently in the consumer I'm limiting it to downloading e.g. Wholesale1 and not Wholesale1T54 as Wholesale1 contains steps 0-36 which already is more than we pull in live: that data only goes up to 12 steps. I can remove these limits of course and pull the T54 files as well, but just wanted to let you know that models trained using the full forecast horizon will be starved for that data when running in production currently.

All these concessions are made in the name of trying to keep consistency between the live and historic data, as it was my undestanding that was the desirable end goal - however, if instead it's better to have more available for training such that we can better inform what is pulled from Live, that also makes sense to me as a motive. Let me know what you think is best!

**Comment by JackKelly** [comment]
although, I should check: is it _possible_ to get 54hr forecasts from UK Met Office in production?!

**Comment by devsjc** [comment]
> Even so, I'd be very keen to have 54-hour NWPs for the full history for our R&D
I'll make sure that downloads as well then.

> is it possible to get 54hr forecasts from UK Met Office in production?
Yes it is, althoug we would have to further upgrade our subscription as that would more than quadruple our data throughput!

**Comment by devsjc** [comment]
Just discovered I also don't have permission to use docker on leonardo either! Does anyone, or is it just not installed?

**Comment by JackKelly** [comment]
Ah, oops, sorry - I've just checked on `leonardo`. It turns out that you had minimal permissions (the only group you were assigned to was the `sol` group!). I've just added you to these groups: `docker sudo ocf`.

(If anyone needs to add users to a Linux machine in the future, please see [these step-by-step instructions for how to add users to the correct groups](https://docs.google.com/document/d/1rzbLjTbAjbzBxqC-9VtVHgnPGYFN7zohFn2K2iL3CNs/edit#heading=h.33i04yhd7jgt))

**Comment by JackKelly** [comment]
I think I've fixed `scripts/download_UK_Met_Office_NWPs_from_CEDA.sh`.

I'm running it now on `leonardo`. I'm running it over the full time horizon of the UKV dataset, so it'll download any missing files it finds. e.g. there were some missing for 2021-11-08.

**Comment by JackKelly** [comment]
OK, the script appears to have worked, so we now have data from 2016 to 2023-05-05T18:00
